#call python run_scrapy.py
from subprocess import call
import time

# call("scrapy crawl teams -a usr=root -a pwd=PASSWORD -a team=0 --nolog", shell=True)
# call("scrapy crawl teams -a usr=root -a pwd=PASSWORD -a team=1 --nolog", shell=True)
# call("scrapy crawl teams -a usr=root -a pwd=PASSWORD -a team=2 --nolog", shell=True)
# call("scrapy crawl teams -a usr=root -a pwd=PASSWORD -a team=3 --nolog", shell=True)
# call("scrapy crawl teams -a usr=root -a pwd=PASSWORD -a team=4 --nolog", shell=True)
# call("scrapy crawl teams -a usr=root -a pwd=PASSWORD -a team=5 --nolog", shell=True)
# call("scrapy crawl teams -a usr=root -a pwd=PASSWORD -a team=6 --nolog", shell=True)
# call("scrapy crawl teams -a usr=root -a pwd=PASSWORD -a team=7 --nolog", shell=True)
# call("scrapy crawl teams -a usr=root -a pwd=PASSWORD -a team=8 --nolog", shell=True)
# call("scrapy crawl teams -a usr=root -a pwd=PASSWORD -a team=9 --nolog", shell=True)
# call("scrapy crawl teams -a usr=root -a pwd=PASSWORD -a team=10 --nolog", shell=True)
# call("scrapy crawl teams -a usr=root -a pwd=PASSWORD -a team=11 --nolog", shell=True)
# call("scrapy crawl teams -a usr=root -a pwd=PASSWORD -a team=12 --nolog", shell=True)
# call("scrapy crawl teams -a usr=root -a pwd=PASSWORD -a team=13 --nolog", shell=True)
# call("scrapy crawl teams -a usr=root -a pwd=PASSWORD -a team=14 --nolog", shell=True)
# call("scrapy crawl teams -a usr=root -a pwd=PASSWORD -a team=15 --nolog", shell=True)
# call("scrapy crawl teams -a usr=root -a pwd=PASSWORD -a team=16 --nolog", shell=True)
# call("scrapy crawl teams -a usr=root -a pwd=PASSWORD -a team=17 --nolog", shell=True)
# call("scrapy crawl teams -a usr=root -a pwd=PASSWORD -a team=18 --nolog", shell=True)
# call("scrapy crawl teams -a usr=root -a pwd=PASSWORD -a team=19 --nolog", shell=True)
# call("scrapy crawl teams -a usr=root -a pwd=PASSWORD -a team=20 --nolog", shell=True)
# call("scrapy crawl teams -a usr=root -a pwd=PASSWORD -a team=21 --nolog", shell=True)
# call("scrapy crawl teams -a usr=root -a pwd=PASSWORD -a team=22 --nolog", shell=True)
# call("scrapy crawl teams -a usr=root -a pwd=PASSWORD -a team=23 --nolog", shell=True)
# call("scrapy crawl teams -a usr=root -a pwd=PASSWORD -a team=24 --nolog", shell=True)
# call("scrapy crawl teams -a usr=root -a pwd=PASSWORD -a team=25 --nolog", shell=True)
# call("scrapy crawl teams -a usr=root -a pwd=PASSWORD -a team=26 --nolog", shell=True)
# call("scrapy crawl teams -a usr=root -a pwd=PASSWORD -a team=27 --nolog", shell=True)
# call("scrapy crawl teams -a usr=root -a pwd=PASSWORD -a team=28 --nolog", shell=True)
# call("scrapy crawl teams -a usr=root -a pwd=PASSWORD -a team=29 --nolog", shell=True)
# call("scrapy crawl nhl -a usr=root -a pwd=PASSWORD --nolog", shell=True)